### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by stuaxo**
Fix a couple of links where files have changed name.

### CODE REVIEW

**Comment by stuaxo** [comment]
Clipper is now available under the Boost license, wasn't sure if I should update the text on that too (though it's still very permissible, so :man_shrugging: )

**Comment by cubicool** [comment]
Is it still being worked on?

**Comment by stuaxo** [comment]
There's an update here, it seems like it is, if slowly
https://sourceforge.net/projects/polyclipping/

And there are a couple of recent commits.

**Review by cubicool — APPROVED** [review]

**Comment by stuaxo** [comment]
Fun to get a notification on this, it gave me an excuse to check out Clipper - and it seems there is a newer, better Clipper 2 now - still under the more sane Boost license (vs the special license they had before)   https://github.com/AngusJohnson/Clipper2

**Comment by cubicool** [comment]
That's actually really great to hear; I'll check it out. I'm working
on setting up a project both showing--in a general sense--and USE
Cairo + WebAssembly, and need to bring things up to date. There are a
lot of ways the Canvas API really sucks, and despite the plethora of
"wrapper" libraries in JavaScript, things still feel pretty awful. So,
back to what I know best. :)

Also, the project I have in my mind would be best suited NOT exposing
the raw drawing/vector data, and so using WebAssembly with something
lower-level to simply blit pixels to a colorbuffer in the browser
suits me fine. I'm having to ALSO throw in SDL2 to actually PUSH the
Cairo source pixel data into the appropriate browser element, but
that's no biggy; EMSDK has great support for SDL, and I'm already very
familiar with how to get Cairo itself to work in weird places.

One day, HOPEFULLY, the Cairo API will just be in C++, and Cairou can
change over to being something even MORE generic.

You might also be interested in the CMake setup I've been working on,
which builds zlib/libpng/pixman/libcairo together statically, no fuss.
I've tested it in GCC, Clang, WSL2+MSVC and EMSDK... all with no
issues. Just getting that whole "stack" to work with a single CMake
command will go a long way, IMHO.

**Comment by stuaxo** [comment]
Tangentially relevant - this thread on the framework DosLike and how that ended up on the web -

https://mobile.twitter.com/Mattias_G/status/1536307001214619648

While the approach is probably different it's interesting reading about the road to simplicity on that API, ending up with something very compatible with different build systems, C and C++ and the web.

**Comment by stuaxo** [comment]
Had a bit more time to read your comment this morning, it all looks very interesting - especially the building statically part, which solves a lot of issues.

Cairos non mainstream backends have a real chicken and egg problem:  hardly anyone uses them, because it's not easy to set up and use along side the system version.

If cairos backends worked using as loadable plugins that would solve the issue, but since it doesn't being able to easily use static builds gets around this, it must have been a pain to get do get cmake to cooperate completely.

**Pull request merged**
